# Generated by Django 2.2.5 on 2021-08-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210807_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedday',
            options={'verbose_name': 'Booked Day', 'verbose_name_plural': 'Booked Days'},
        ),
    ]
