# Generated by Django 2.2.5 on 2021-08-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210807_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedday',
            old_name='revervation',
            new_name='reservation',
        ),
    ]
